final List<Map<String, dynamic>> masterAstrologers = [
  {
    'name': 'Yogini Meera',
    'image': 'assets/images/meera.jpg',
    'specialties': ['Palmistry', 'Crystal Healing', 'Love'],
    'experience': 12,
    'languages': ['English'],
    'rating': 5.0,
    'price': 30,
    'isOnline': true,
    'bio': 'Deep spiritual insights through ancient palmistry and crystal therapy.',
  },
  {
    'name': 'Astro Priya',
    'image': 'assets/images/priya.jpg',
    'specialties': ['Tarot Reading', 'Numerology', 'Tarot', 'Career'],
    'experience': 8,
    'languages': ['English', 'Hindi', 'Tamil'],
    'rating': 4.9,
    'price': 25,
    'isOnline': true,
    'bio': 'Empowering your life path decisions using Tarot keys and Numerology alignments.',
  },
  {
    'name': 'Acharya Shivam',
    'image': 'assets/images/shivam.jpg',
    'specialties': ['Vedic Astrology', 'Vastu', 'Kundli', 'Marriage'],
    'experience': 15,
    'languages': ['English', 'Hindi'],
    'rating': 4.8,
    'price': 20,
    'isOnline': true,
    'bio': 'Specialist in Kundli matchmaking, Vastu architecture, and Vedic remediations.',
  },
  {
    'name': 'Swami Anand',
    'image': 'assets/images/anand.jpg',
    'specialties': ['Vedic', 'Gemology', 'Kundli'],
    'experience': 20,
    'languages': ['Hindi', 'Marathi'],
    'rating': 4.7,
    'price': 35,
    'isOnline': false,
    'bio': 'Gemstone recommendations and Vedic chart mappings based on ancient scriptures.',
  },
];
