// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkGt3cm94SVtTW7_raEwfmpvwdUR-tU5E',
    appId: '1:24968482924:web:4e49dc39d76fadd7d3c849',
    messagingSenderId: '24968482924',
    projectId: 'omastro-42ea9',
    authDomain: 'omastro-42ea9.firebaseapp.com',
    databaseURL: 'https://omastro-42ea9-default-rtdb.firebaseio.com',
    storageBucket: 'omastro-42ea9.firebasestorage.app',
    measurementId: 'G-EXVPVC2BHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABys7lFHDfQ5eCs5rh9wZeXhM3KzZCHdM',
    appId: '1:24968482924:android:ed18a3ec6fd16423d3c849',
    messagingSenderId: '24968482924',
    projectId: 'omastro-42ea9',
    databaseURL: 'https://omastro-42ea9-default-rtdb.firebaseio.com',
    storageBucket: 'omastro-42ea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrtL1w1KhW-L5vL3JRfzlzEIR3q3cSrs',
    appId: '1:24968482924:ios:71cdfd4f3d41d96ed3c849',
    messagingSenderId: '24968482924',
    projectId: 'omastro-42ea9',
    databaseURL: 'https://omastro-42ea9-default-rtdb.firebaseio.com',
    storageBucket: 'omastro-42ea9.firebasestorage.app',
    iosClientId: '24968482924-o5nbvf6ig2438a65q8vc91e4q2fas2ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.omastro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrtL1w1KhW-L5vL3JRfzlzEIR3q3cSrs',
    appId: '1:24968482924:ios:71cdfd4f3d41d96ed3c849',
    messagingSenderId: '24968482924',
    projectId: 'omastro-42ea9',
    databaseURL: 'https://omastro-42ea9-default-rtdb.firebaseio.com',
    storageBucket: 'omastro-42ea9.firebasestorage.app',
    iosClientId: '24968482924-o5nbvf6ig2438a65q8vc91e4q2fas2ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.omastro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkGt3cm94SVtTW7_raEwfmpvwdUR-tU5E',
    appId: '1:24968482924:web:60f4c72a628a4f6cd3c849',
    messagingSenderId: '24968482924',
    projectId: 'omastro-42ea9',
    authDomain: 'omastro-42ea9.firebaseapp.com',
    databaseURL: 'https://omastro-42ea9-default-rtdb.firebaseio.com',
    storageBucket: 'omastro-42ea9.firebasestorage.app',
    measurementId: 'G-66BWZE8PCG',
  );
}
